[package]
name = "angry-apes"
version = "0.1.0"
edition = "2021"

[dependencies]
# bevy = "0.6"
bevy = { version = "0.6", features = ["dynamic"] }
bevy_embedded_assets = "0.2"
bevy_prototype_lyon = "0.4"
lyon_tessellation = "0.17"
